# Generated by Django 4.0.4 on 2022-05-13 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=50)),
                ('keycaps', models.CharField(max_length=50)),
                ('switches', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('full sized', 'Full Sized'), ('1800 compact', '1800 Compact'), ('tenkeyless', 'Tenkeyless'), ('75%', '75%'), ('65%', '65%'), ('60%', '60%'), ('40%', '40%'), ('number pad', 'Number Pad'), ('Macro pad', 'Macro Pad')], max_length=50)),
                ('plate', models.CharField(blank=True, max_length=50, null=True)),
                ('stabilizers', models.CharField(blank=True, max_length=50, null=True)),
                ('split', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
