# Generated by Django 4.0.4 on 2022-05-14 21:13

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_keyboard_case_alter_keyboard_keycaps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='likes',
            field=models.ManyToManyField(related_name='keyboard_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
