# Generated by Django 4.0.4 on 2022-05-14 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_keyboard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='keyboard_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
